// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PMS_api.Data;

#nullable disable

namespace PMS_api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20221026190047_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PMS_api.Model.AllowedStudents", b =>
                {
                    b.Property<long>("student_roll_no")
                        .HasColumnType("bigint");

                    b.Property<long>("company_id")
                        .HasColumnType("bigint");

                    b.HasKey("student_roll_no", "company_id");

                    b.HasIndex("company_id");

                    b.ToTable("AllowedStudents");
                });

            modelBuilder.Entity("PMS_api.Model.Companies", b =>
                {
                    b.Property<long>("company_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("company_id"), 1L, 1);

                    b.Property<string>("company_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("package")
                        .HasColumnType("real");

                    b.HasKey("company_id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("PMS_api.Model.Placed", b =>
                {
                    b.Property<long>("roll_number")
                        .HasColumnType("bigint");

                    b.Property<long>("company_id")
                        .HasColumnType("bigint");

                    b.HasKey("roll_number");

                    b.HasIndex("company_id");

                    b.ToTable("Placed");
                });

            modelBuilder.Entity("PMS_api.Model.Student", b =>
                {
                    b.Property<long>("roll_number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("roll_number"), 1L, 1);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("roll_number");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("PMS_api.Model.User", b =>
                {
                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userName");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            userName = "admin",
                            pass = "1234"
                        });
                });

            modelBuilder.Entity("PMS_api.Model.AllowedStudents", b =>
                {
                    b.HasOne("PMS_api.Model.Companies", "Companies")
                        .WithMany()
                        .HasForeignKey("company_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS_api.Model.Student", "Student")
                        .WithMany()
                        .HasForeignKey("student_roll_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Companies");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PMS_api.Model.Placed", b =>
                {
                    b.HasOne("PMS_api.Model.Companies", "Companies")
                        .WithMany()
                        .HasForeignKey("company_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS_api.Model.Student", "Student")
                        .WithMany()
                        .HasForeignKey("roll_number")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Companies");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
